version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: strapi_db
      POSTGRES_USER: strapi_user
      POSTGRES_PASSWORD: Biencopiado1234!
    volumes:
      - postgres_data:/var/lib/postgresql/data

  strapi:
    build:
      context: .
    depends_on:
      - postgres

volumes:
  postgres_data: